spring:

  messages:
    baseName: messages
    encoding: UTF-8
    fallbackToSystemLocale: false

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  output:
    ansi:
      enabled: always

  data:
    mongodb:
      host: localhost
      port: 27017
      database: hw09
      auto-index-creation: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  thymeleaf:
    cache: false

  logging:
    level:
      root: OFF
      #Отключаем шумные пакеты
      org.springframework.boot.autoconfigure: OFF
      org.springframework.security: OFF

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
