spring:
  datasource:
    url: jdbc:h2:mem:maindb
  shell:
    interactive:
      enabled: true
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql